services:
  begostudy:
    image: phucmarc0/gostudybe:v1.2
    build:
      context: .
      dockerfile: BE_GOStudy/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=${CONNECTION_STRING}
    ports:
      - "8080:80"
    labels:
      io.portainer.accesscontrol.teams: go-study
      io.portainer.accesscontrol.restricted
    restart: always
    networks:
      - go-study-networks
  
networks:
  go-study-networks:
    name: go-study-networks
