on:
    push: 
        branches: 
            - main

jobs:
    build-application:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v3
            - name: Dockerhub Login
              uses: docker/login-action@v3.1.0
              with:
                  username: ${{secrets.DOCKER_USERNAME}}
                  password: ${{secrets.DOCKER_TOKEN}}
            - name: Build Image And Push To Dockerhub
              run: docker compose -f BE_GOStudy/docker-compose.yml build begostudy && docker compose -f BE_GOStudy/docker-compose.yml push begostudy
    
    deploy-backend:
        runs-on: arisa-server
        needs: [build-application]
        env:
            CONNECTION_STRING: Server=${{secrets.DB_HOST}},${{secrets.DB_PORT}};Database=${{secrets.DATABASE_NAME}};User=${{secrets.DB_USERNAME}};Password=${{secrets.DB_PASSWORD}}
        steps:
            - name: Checkout Code
              uses: actions/checkout@v3
            - name: Dockerhub Login
              uses: docker/login-action@v3.1.0
              with:
                username: ${{secrets.DOCKER_USERNAME}}
                password: ${{secrets.DOCKER_TOKEN}}
            - name: Shop BE_GOStudy API
              run: docker compose -f BE_GOStudy/docker-compose.yml -p gostudy-api down begostudy --rmi all
            
            - name: Deploy API
              run: docker compose -f BE_GOStudy/docker-compose.yml -p gostudy-api up -d begostudy